from dotenv import dotenv_values

# Configuration loading from .env
CONFIG = dotenv_values(".env")
DATABASE_URI = f"postgresql+psycopg2://{CONFIG['POSTGRES_USER']}:{CONFIG['POSTGRES_PASSWORD']}@localhost:{CONFIG['POSTGRES_PORT']}/{CONFIG['POSTGRES_DB']}"
RECORD_RETRIEVAL_LIMIT = int(CONFIG["RECORD_RETRIEVAL_LIMIT"])
API_KEY = CONFIG["API_KEY"]
PRODUCER_THREAD_COUNT = int(CONFIG.get("PRODUCER_THREAD_COUNT", 4))
CONSUMER_THREAD_COUNT = int(CONFIG.get("CONSUMER_THREAD_COUNT", 2))
SEMAPHOR_THREAD_COUNT = int(CONFIG.get("SEMAPHOR_THREAD_COUNT", 10))
DEFAULT_ADDRESS = CONFIG.get("DEFAULT_ADDRESS", "default_ethereum_address")
DEV_MODE = CONFIG.get('DEV_MODE')
DEV_MODE_ENDING_MULTIPLE = int(CONFIG.get("DEV_MODE_ENDING_MULTIPLE"))
DEV_STEP = int(CONFIG.get("DEV_STEP"))
DEV_PRODUCER_THREAD_COUNT = int(CONFIG.get("DEV_PRODUCER_THREAD_COUNT"))
API_RATE_LIMIT_DELAY = float(CONFIG.get("API_RATE_LIMIT_DELAY"))
SAVE_BATCH_LIMIT = int(CONFIG.get("SAVE_BATCH_LIMIT"))
BASE_BLOCK_ATTEMPT = int(CONFIG.get("BLOCK_ATTEMPT1"))
BLOCK_ATTEMPTS = [int(CONFIG.get("BLOCK_ATTEMPT2")) ,int(CONFIG.get("BLOCK_ATTEMPT3")) ,int(CONFIG.get("BLOCK_ATTEMPT4")) ,int(CONFIG.get("BLOCK_ATTEMPT5")) ,int(CONFIG.get("BLOCK_ATTEMPT6")) ,int(CONFIG.get("BLOCK_ATTEMPT7")) ,int(CONFIG.get("BLOCK_ATTEMPT8")) ,int(CONFIG.get("BLOCK_ATTEMPT9")), int(CONFIG.get("BLOCK_ATTEMPT10"))]
TEST_MODE = None
TEST_MODE_STARTING_BLOCK = None
TEST_MODE_END_BLOCK = None
